/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paket;

/**
 *
 * @author my acer
 */
public class panelformdua extends javax.swing.JPanel {

    /**
     * Creates new form panelformdua
     */
    public panelformdua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        satu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dua = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        total_ab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PENGURANGAN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Bilangan ke Satu :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        add(satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 53, 34));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Bilangan ke dua :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        add(dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 55, 34));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));
        add(total_ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 72, 31));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("HASIL ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a=Integer.valueOf(satu.getText());
        int b=Integer.valueOf(dua.getText());
        int Hasil=a-b;
     total_ab.setText(""+Hasil);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dua;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField satu;
    private javax.swing.JTextField total_ab;
    // End of variables declaration//GEN-END:variables
}
